### ISSUE TITLE
ControlNet with Anime

### ISSUE THREAD

**Issue by SlimeVRX** [camenduru/controlnet-colab#2]
Hello!

Amazing! The author just posted a tutorial to use ControlNet with Anime [AnythingV3] [Link](https://github.com/lllyasviel/ControlNet/discussions/12)

I'm having a problem:

I run on Colab, the computer does not have enough VRAM to merge model.
Need at least 21.11 Gb RAM to load 3 model.
Can someone share with me the model after the merge "control_any3.pth"?
I need "Canny edge" model.

Thank you very much!

**Comment by camenduru** [comment]
Now we have lots of anime models 🎉
