### ISSUE TITLE
Can't use transfer control to other models colab

### ISSUE THREAD

**Issue by esdrico** [camenduru/controlnet-colab#3]
Hello, i'm having these errors when i try to use the colab in colab free plan: 
![image](https://user-images.githubusercontent.com/110066914/218333211-84e122d3-ca67-4de5-96c0-dabd56c5ec0d.png)

![image](https://user-images.githubusercontent.com/110066914/218333329-fd105d62-c6bc-4cac-94dc-8ed87009ac32.png)

The system ram goes really up and it stops:
![image](https://user-images.githubusercontent.com/110066914/218333424-1cddc4ab-a877-4f02-900c-af170727405e.png)
I'm using control_sd15_openpose

**Comment by camenduru** [comment]
Hi @esdrico 👋 this is not possible with free colab. We are looking for a way to reduce the ram usage.

**Comment by SlimeVRX** [comment]
I found a way to reduce ram using Colab, I need 2 days
Note: the job will be the same as task 2.2 [Link](https://colab.research.google.com/github/discus0434/custom-depth2image-playground/blob/main/Custom_Depth_to_Image_Playground.ipynb#scrollTo=buIq6Ro3YMYe), no need to load 3 models at the same time, take out the necessary things, save, delete ram. The best case, if the output is 5Gb, the computer will only have 5Gb at most.

**Comment by SlimeVRX** [comment]
Sorry, I don't have a task to do this, I will update when there is a related task.

Currently I am using the merger model from:
@nakayama [DeDeDe](https://huggingface.co/nakayama/DeDeDe/tree/main/controlnet) Merger
@toyxyz [Anything3](https://huggingface.co/toyxyz/Control_any3/tree/main) Merger

Sorry for not being able to keep my promise!

**Comment by camenduru** [comment]
please use this https://huggingface.co/webui/ControlNet-modules-safetensors/tree/main 723MB🥳

**Comment by camenduru** [comment]
I think we solved this hehe
