### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for ControlLDM

### ISSUE THREAD

**Issue by haofanwang** [camenduru/controlnet-colab#5]
[stable_diffusion_inpainting_controlnet_colab.ipynb](https://colab.research.google.com/github/camenduru/controlnet-colab/blob/main/stable_diffusion_inpainting_controlnet_colab.ipynb?authuser=1) doesn't work.

**Comment by camenduru** [comment]
Hi @haofanwang 👋 thanks for the info ❤ right now not all models are compatible with controlnet

**Comment by camenduru** [comment]
Hi @haofanwang 👋 this one is working please try it https://github.com/camenduru/stable-diffusion-webui-colab/blob/v2.0/stable_diffusion_inpainting_webui_colab.ipynb
